name: Update Progress Badge

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger option

jobs:
  update-progress-badge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install requests pybadges matplotlib

    - name: Calculate Progress and Update README
      run: |
        python src/calculate_progress.py \
          --owner "${{ github.repository_owner }}" \
          --token "${{ secrets.GITHUB_TOKEN }}" \
          --readme-path "README.md" \
          --badge-path "progress.svg"

    - name: Commit changes before pulling
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add README.md progress.svg progress_graph.png
        git commit -m "Committing changes before pulling"

    - name: Pull changes with rebase
      run: git pull --rebase origin master

    - name: Commit final changes
      run: |
        git add README.md progress.svg progress_graph.png
        git diff-index --quiet HEAD || git commit -m "Update progress badge"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
