name: Update Progress Badge

on:
  push:
    paths:
      - progress.json
      - README.md

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Read Progress Data
      id: progress
      run: |
        # Read total and completed days from the JSON file
        total_days=$(jq '.total_days' progress.json)
        completed_days=$(jq '.completed_days' progress.json)

        # Calculate percentage
        percentage=$((completed_days * 100 / total_days))
        echo "progress=$percentage" >> $GITHUB_ENV

    - name: Update README with Progress Badge
      run: |
        # Update README with the progress badge
        badge_url="![Progress Badge](https://img.shields.io/static/v1?label=Challenge&message=${{ env.progress }}%25%20Complete&color=brightgreen&style=flat-square)"
        sed -i "s|<progress-placeholder>|$badge_url|g" README.md

    - name: Commit Changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add README.md
        git commit -m "Update progress badge"
        git push
