name: Delete Environment (default settings)

on:
  delete:
    branches-ignore:
      - main
  workflow_dispatch:  # This will allow manual triggers

jobs:
  clean-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Clear Cache
        run: |
          echo "Clearing Cache"
          rm -rf ~/.cache/* # You can clear specific cache directories as needed
